path: /content/drive/MyDrive/anaemiadetect/data/dorsal.v1i.yolov8
train: train/images
val: valid/images
test: test/images

nc: 1  # number of classes (just 'nail')
names: ['nail']  # class names